source 'https://cdn.cocoapods.org/'

inhibit_all_warnings!

target 'PhunwareMappingSample' do
  platform :ios, '13.0'
  use_frameworks!

  pod 'PhunwareMapping', '~> 1.7.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
