source 'https://cdn.cocoapods.org/'

inhibit_all_warnings!

target 'PhunwareMappingSample' do
  platform :ios, '15.5'
  use_frameworks!

  pod 'PhunwareFoundation'
  pod 'PhunwareCorePlugin'
  pod 'PhunwareMapping', :git => 'https://github.com/phunware/maas-mapping-module-ios.git', :tag => '1.9.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
